# Слабые контрастивные аугментации для SimCLR
# Для начала обучения или при нестабильности
_target_: src.data_loaders.ssl_transforms.ContrastiveTransform

input_size: [128, 313]
strength: "weak"
noise_dir: null
