_target_: src.modules.heads.ArcFaceHead
# Параметры ArcFace
s: 30.0  # Scale (радиус гиперсферы). Обычно 30-64.
m: 0.50  # Margin (угловой отступ). Чем больше, тем сложнее модели, но кластеры плотнее.
dropout: 0.3