model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss" # Будет переопределяться системой, если нужно
  mode: "min"
  save_top_k: 1
  save_last: true
  filename: "{epoch:02d}-{val_loss:.4f}"

reporter:
  _target_: src.utils.reporter.UniversalReporter # Наш новый репортер
  _recursive_: false