defaults:
  - model: efficientnet # или efficientnet
  - frontend: identity
  - head: projection # Возвращаем проектор!
  - loss: ntxent     # Возвращаем SimCLR лосс
  - data: ssl_data
  - augmentation: contrastive_strong
  - augmentation@val_augmentation: val
  - optimizer: adamw_ssl
  - scheduler: cosine
  - trainer: ssl_trainer
  - _self_

project_name: "Phase2_SimCLR_Final"

ssl_mode: "contrastive"  # <--- ВАЖНО

scheduler:
  T_max: 100